-- SQL INSERT statements for Headshot Photographers
-- Generated from provided data
-- Categories stored as TEXT (comma-separated if multiple)
-- Slugs are auto-generated by database trigger, but provided here for clarity

-- Helper function to generate slug (matches database trigger logic)
-- Note: Database has a trigger that ensures unique slugs automatically
-- Status enum values: 'Pending', 'Live', 'Rejected', 'Inactive'
-- Plan enum values: 'Free', 'Basic', 'Pro', 'Premium'

INSERT INTO listings (
  slug,
  listing_name,
  website,
  email,
  city,
  state,
  categories,
  status,
  plan,
  created_at,
  updated_at
) VALUES
-- Los Angeles, CA
('mt-photography-michael-tari', 'MT Photography (Michael Tari)', 'https://www.mtphotographs.com/', 'michaeltaristudios@gmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('the-headshot-truck', 'The Headshot Truck', 'https://www.headshottruck.com/', 'hello@capturely.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('actor-photo-la', 'Actor Photo LA', 'http://www.actorphotola.com/', 'gbrown777@pipeline.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('budget-headshots', 'Budget Headshots', 'https://www.budgetheadshots.com/', 'budgetheadshots@gmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('headshot-shop-la', 'Headshot Shop LA', 'https://headshotshopla.com/actor-headshots', 'joseph@puhy.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('anthony-mongiello-photography', 'Anthony Mongiello Photography', 'https://www.anthonymongiello.com/', 'anthonymongiello@gmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('bella-saville', 'Bella Saville', 'https://www.bellasavillephotography.com/', 'bellasavillephotography@gmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('brad-buckman', 'Brad Buckman', 'https://www.buckmanheadshots.com/', 'studio@bradbuckman.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('bradford-rogne', 'Bradford Rogne', 'https://rognephoto.com/', 'Info@RognePhoto.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('cathryn-farnsworth', 'Cathryn Farnsworth', 'https://www.cathrynfarnsworthheadshots.com/', 'booking@cathrynfarnsworth.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('chris-evan-photography', 'Chris Evan Photography', 'https://www.chrisevanphotography.com/', 'cephoto.manager@gmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('dana-patrick', 'Dana Patrick', 'https://www.danapatrickphoto.com/', 'booking@danapatrickphoto.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('david-muller-photography', 'David Muller Photography', 'http://www.davidmullerphotography.com/', 'studio@davidmullerphotography.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('dylan-patrick', 'Dylan Patrick', 'https://dylanpatrick.com/home/cinematic-headshots', 'dylan@dylanpatrick.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('james-depietro', 'James Depietro', 'https://headshotsbyjd.com/', 'james_d_123@hotmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('jessica-sherman-headshots', 'Jessica Sherman Headshots', 'http://jessicashermanphotography.com/', 'jessica@jessicashermanphotography.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('ken-weingart-photography', 'Ken Weingart Photography', 'https://www.kenweingart.com/headshot-photographer/', 'ken@weingartphoto.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('kenneth-dolin', 'Kenneth Dolin', 'https://www.kennethdolin.com/actors', 'info@kennethdolin.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('la-photospot-todd-tyler', 'LA PhotoSpot / Todd Tyler', 'https://www.laphotospot.com/', 'info@LAphotoSpot.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('laura-burke', 'Laura Burke', 'https://www.lauraburkephotography.com/', 'lauraburkephotography@gmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('marc-cartwright-headshots', 'Marc Cartwright Headshots', 'https://www.marccartwrightheadshots.com/', 'HeadshotsByMarc@gmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('michael-hiller', 'Michael Hiller', 'http://www.michaelhiller.com/', 'michaelhiller777@gmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('michael-roud-photography', 'Michael Roud Photography', 'https://michaelroud.com/', 'info@michaelroud.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('molly-pan-photography', 'Molly Pan Photography', 'https://www.mollypanphoto.com/', 'mollypanphotography@gmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('monesson-photography-josh-monesson', 'Monesson Photography / Josh Monesson', 'https://www.monessonphotography.com/', 'joshuamonesson@yahoo.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('paul-gregory-headshots', 'Paul Gregory Headshots', 'https://www.paulgregoryphotography.com/', 'paulgregoryphoto@me.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('sergio-garcia', 'Sergio Garcia', 'https://www.sergiogarciaheadshots.com/', 'i.sergiogarcia@me.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('sosa-headshots', 'Sosa Headshots', 'https://www.shotbysosa.com/', 'sosashotit@gmail.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('stepanyan-photography-seda-stepanyan', 'Stepanyan Photography / Seda Stepanyan', 'https://stepanyanphotography.com/', 'seda@stepanyanphotography.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('stephanie-girard', 'Stephanie Girard', 'https://www.stephgirardheadshots.com/', 'studio@stephgirardheadshots.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('studio-roy', 'Studio Roy', 'http://studioroy.com/', 'lisa@studioroy.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('the-light-committee', 'The Light Committee', 'https://thelightcommittee.com/actor-headshots/', 'rafael@thelightcommittee.com', 'Los Angeles', 'CA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),

-- New York, NY
('baza-productions', 'Baza Productions', 'https://baza.productions', 'baza4studio@gmail.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('ben-esner-photography', 'Ben Esner Photography', 'https://benesner.com/', 'ben@benesner.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('ceoportriat', 'CEOportriat', 'https://www.ceoportrait.com/', 'info@ceoportrait.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('chris-macke-photography', 'Chris Macke Photography', 'https://www.mackephotography.com/', 'chris@mackephotography.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('christian-webb', 'Christian Webb', 'https://www.christianwebbphoto.com/projects', 'chris@christianwebbphoto.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('city-headshots', 'City Headshots', 'https://www.cityheadshots.com/', 'info@cityheadshots.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('david-genik', 'David Genik', 'https://www.davidgenik.com/', 'david@davidgenik.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('david-noles', 'David Noles', 'http://www.davidnoles.com/', 'hello@davidnoles.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('downtown-headshots-nyc', 'Downtown Headshots NYC', 'https://downtownheadshotsnyc.com/', 'cb@cbimage.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('emily-lambert-photography', 'Emily Lambert Photography', 'https://www.emilylambertphoto.com/', 'info@emilylambertphoto.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('hancock-headshots', 'Hancock Headshots', 'http://www.hancockheadshots.com/', 'studio@hancockheadshots.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('jeffrey-mosier-photography', 'Jeffrey Mosier Photography', 'http://www.jeffreymosierphotography.com/', 'jeffreymosierphotography01@gmail.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('jeremy-folmer-photography', 'Jeremy Folmer Photography', 'https://www.jeremyfolmer.com/', 'mail@jeremyfolmer.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('jessica-osber-photography', 'Jessica Osber Photography', 'https://osberphotos.com/', 'info@osberphotos.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('joe-henson', 'Joe Henson', 'https://www.joehenson.com/', 'joe@joehenson.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('joe-jenkins', 'Joe Jenkins', 'https://www.joejenkinsphoto.com/', 'info@joejenkinsphoto.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('jordan-matter-studio', 'Jordan Matter Studio', 'https://www.jordanmatter.com/photography/head-shots', 'info@jordanmatter.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('jw-headshots', 'JW Headshots', 'https://www.jwheadshots.com/', 'jamiya@jwheadshots.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('laura-volpacchio-photography', 'Laura Volpacchio Photography', 'https://lauravolpacchiophotography.com/', 'hello@lauravolpacchiophotography.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('leslie-hassler-studio', 'Leslie Hassler Studio', 'https://www.lesliehassler.com/actors', 'leslie@lesliehassler.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('lindsay-van-norman-photography', 'Lindsay Van Norman Photography', 'https://www.lindsayvannorman.com/', 'lindsayvannormanphoto@gmail.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('mark-reay-photography', 'Mark Reay Photography', 'http://markheadshots.com/', 'markreay66@yahoo.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('melany-bernier', 'Melany Bernier', 'http://www.melanybernier.com/', 'info@melanybernier.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('melissa-hamburg-photography', 'Melissa Hamburg Photography', 'http://www.melissahamburg.com/', 'melissahamburgphotography@gmail.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('mia-isabella-photography', 'Mia Isabella Photography', 'https://www.miaisabellaphotography.com/', 'miaisa@gmail.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('michael-levy-photography', 'Michael Levy Photography', 'https://www.michaellevyphoto.com/', 'michael@mjlevy.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('nile-scott-studios', 'Nile Scott Studios', 'https://nilescottstudios.com/', 'nile@nilescottstudios.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('pic-me-headshots', 'Pic Me! Headshots', 'https://www.picmeheadshots.com/', 'contact@picmeheadshots.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('peter-hurley', 'Peter Hurley', 'https://peterhurley.com/', 'info@peterhurley.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('philip-kessler-studio', 'Philip Kessler Studio', 'http://www.philipkesslerphotography.com/', 'philkphotos@gmail.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('ricardo-birnbaum-photographer', 'Ricardo Birnbaum Photographer', 'https://www.ricardobirnbaumphotography.com/', 'ricardobirnbaumphotography@gmail.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('suburban-photography', 'Sub/Urban Photography', 'http://www.sub-urbanphotography.com/', 'info@sub-urbanphotography.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('susan-stripling', 'Susan Stripling', 'https://www.susanstripling.com/', 'susan@susanstripling.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('ted-ely-headshots', 'Ted Ely Headshots', 'https://tedely.com/', 'studio@tedely.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('tess-steinkolk-brown-dog-productions', 'Tess Steinkolk / Brown Dog Productions', 'https://www.tesssteinkolk.com/', 'tess@tsteinkolk.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('todd-estrin-photography', 'Todd Estrin Photography', 'https://www.toddestrinphotography.com/', 'todd@toddestrinphotography.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('xanthe-elbrick-photography', 'Xanthe Elbrick Photography', 'https://www.xantheelbrickphotography.com/headshots.html', 'xelbrickphotography@gmail.com', 'New York', 'NY', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),

-- Chicago, IL
('aaron-gang', 'Aaron Gang', 'https://www.aarongang.com/', 'hello@aarongang.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('janna-giacoppo', 'Janna Giacoppo', 'http://www.jannagiacoppo.com/', 'oneandotherproductions@gmail.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('gretchen-kelley', 'Gretchen Kelley', 'https://www.gretchenkelley.com', 'Info@GretchenKelley.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('jeff-kurysz', 'Jeff Kurysz', 'https://jeffkuryszphotography.com', 'jeffkurysz@gmail.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('joe-mazza', 'Joe Mazza', 'https://www.bravelux.com', 'Joe@bravelux.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('ian-mcclaren', 'Ian McClaren', 'https://www.ianmclaren.com', 'ian@ianphillips-mclaren.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('brian-mcconkey', 'Brian McConkey', 'https://www.brianmcconkeyphotography.com', 'brian@brianmcconkeyphotography.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('collin-quinn-rice', 'Collin Quinn Rice', 'https://www.collinquinnrice.com/photography', 'cquinnheadshots@gmail.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('maia-rosenfeld', 'Maia Rosenfeld', 'https://www.letsdoshots.com', 'maia@letsdoshots.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('popio-stumpf-photography', 'Popio Stumpf Photography', 'https://www.popiostumpf.com', 'info@popiostumpf.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('312-elements-headshot-photography', '312 Elements Headshot Photography', 'https://312elements.com/', 'info@312elements.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('johnny-knight-photo', 'Johnny Knight Photo', 'https://johnnyknightphoto.com', 'hello@johnknight.co.uk', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('kyle-bondeson-photography', 'Kyle Bondeson Photography', 'https://www.kylebondeson.com', 'kyle@kylebondeson.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('mike-sansone-photography', 'Mike Sansone Photography', 'https://mikesansonephotography.com/', 'mike@mikesansonephotography.com', 'Chicago', 'IL', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),

-- Boston, MA
('boston-creative-headshots', 'Boston Creative Headshots', 'http://www.bostoncreativeheadshots.com/', 'dp@bostoncreativeheadshots.com', 'Boston', 'MA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('dina-k-photography', 'Dina K Photography', 'https://dinakphotography.com', 'info@dinakphotography.com', 'Boston', 'MA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('ellen-sargent-korsh-photography', 'Ellen Sargent Korsh Photography', 'http://ellensargentkorsh.com', 'ellenskorsh@gmail.com', 'Boston', 'MA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('erica-derrickson', 'Erica Derrickson', 'https://ericaseye.com', 'ericaderricka@gmail.com', 'Boston', 'MA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('headshots-photography', 'Headshots Photography', 'https://www.headshotsphoto.com/', 'service@headshotsphoto.com', 'Boston', 'MA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('kevin-day-photography', 'Kevin Day Photography', 'https://kevindayphotography.com/potfolio/headshot', 'kevinday710@gmail.com', 'Boston', 'MA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('matthew-guillory-photography', 'Matthew Guillory Photography', 'https://www.mattgphoto.com/galleries/headshots-creatives', 'matt@mattgphoto.com', 'Boston', 'MA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('maura-wayman', 'Maura Wayman', 'https://www.maurawayman.com/actor-headshots/', 'maura@maurawayman.com', 'Boston', 'MA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('niles-scott-studios', 'Niles Scott Studios', 'http://nilescottstudios.com/', 'nile@nilescottstudios.com', 'Boston', 'MA', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),

-- Dallas, TX
('shea-anne-studios', 'Shea Anne Studios', 'https://sheaannestudios.com/', 'info@sheaanne.com', 'Dallas', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('actors-captured-headshots', 'Actors Captured Headshots', 'https://www.actorscapturedheadshots.com/', 'currycarin@gmail.com', 'Dallas', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('trg-headshots', 'TRG Headshots', 'https://www.trgheadshots.com/', 'travis@trgheadshots.com', 'Dallas', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('2mm-headshots', '2mm Headshots', 'https://2mmheadshotsandeventphotography.com/', 'peter@2mmheadshotsandeventphotography.com', 'Dallas', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('mj-marshall-headshots', 'MJ Marshall Headshots', 'https://www.mgmarshallheadshots.com/', 'mgmarshallphotography@gmail.com', 'Dallas', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('headshot-professional-photographers', 'Headshot Professional Photographers', 'https://www.headshotprofessional.com/', 'JoeHeadshotPro@gmail.com', 'Dallas', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),

-- Houston, TX
('calvin-pennick-jr-photography', 'Calvin Pennick JR Photography', 'https://www.calvinpennickjrphotography.com/', 'getinfo@calvinpennickjrphotography.com', 'Houston', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('tonya-dailey-headshots', 'Tonya Dailey Headshots', 'https://tonya-dailey-photography.square.site/', 'booking@tonyadailey.com', 'Houston', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('chris-gillett-liketherazorcom', 'Chris Gillett (liketherazor.com)', 'https://liketherazor.com/', 'info@liketherazor.com', 'Houston', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('tara-flannery-photography', 'Tara Flannery Photography', 'https://taraflannery.com/actor-and-model-headshots', 'tara@taraflannery.com', 'Houston', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('fred-taylor-photography', 'Fred Taylor Photography', 'https://fredtaylorphotography.com/', 'fred@fredtaylorphotography.com', 'Houston', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),

-- San Antonio, TX
('ashley-ball-photography', 'Ashley Ball Photography', 'https://www.ashleyballphotography.com/', 'ashley@ashleyballphotography.com', 'San Antonio', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),

-- Austin, TX
('steve-noreyko-headshots', 'Steve Noreyko Headshots', 'https://www.headshot-photos.com/', 'steve@stevenoreyko.com', 'Austin', 'TX', ARRAY['Headshot Photographers'], 'Live', 'Free', NOW(), NOW()),
('austin-headshots-david-price', 'Austin Headshots (David Price)', 'https://www.austintxheadshots.com/', 'info@davidpricephotography.com', 'Austin', 'TX', 'Headshot Photographers', 'Live', true, 'Free', NOW(), NOW());

-- Note: The database has a trigger that automatically ensures unique slugs
-- If a slug conflict occurs, the trigger will append a number (e.g., slug-1, slug-2)
-- All listings are set to:
--   - status: 'Live' (ready to go live)
--   - active: true
--   - plan: 'Free'
--   - categories: 'Headshot Photographers' (stored as TEXT)

